export interface I18nField {
  en: string;
  ur?: string;
  roman?: string;
  hi?: string;
  ar?: string;
}

/** Matches Flutter [AppLanguage] content resolution keys. */
export type ContentLocale = 'en' | 'ur' | 'roman' | 'ar';

export interface Book {
  id: string;
  title: I18nField;
  titleArabic?: string;
  author?: string;
  speaker: I18nField;
  speakerShortName?: string;
  totalDurationSeconds: number;
  lectureCount: number;
  coverImageUrl: string;
  language: string;
  catalogUpdatedAt?: string;
}

export interface Chapter {
  id: string;
  number: number;
  title: I18nField;
  lectureCount: number;
}

export interface Lecture {
  id: string;
  number: number;
  chapterId: string;
  title: I18nField;
  audioUrl: string;
  durationSeconds: number;
  fileSizeBytes: number;
  description?: string | null;
}

export interface DailyBenefit {
  id: string;
  text: string | I18nField;
  source: string | I18nField;
  textArabic?: string;
}

export interface Catalog {
  version: number;
  book: Book;
  chapters: Chapter[];
  lectures: Lecture[];
  dailyBenefits: DailyBenefit[];
}

export interface AppConfig {
  version: number;
  links: { playStore?: string; appStore?: string; website?: string; youtube?: string };
  contact: { email: string; subject: string };
  share: { message: string };
  about: { appName: string; lecturer: string; lectureCount: number; totalDuration: string };
}

export const SITE_URL = 'https://kitabattawheed.com';

// Cross-promo — "Also by Al Marfa". Al Quran (alquranreader.com) is the
// sister site/app; reciprocal link lives in that repo's footer + About page.
export const ALQURAN_SITE_URL = 'https://alquranreader.com';
export const ALQURAN_PLAY_URL =
  'https://play.google.com/store/apps/details?id=com.almarfa.alquran' +
  '&utm_source=tawheedweb&utm_medium=web&utm_campaign=cross-promo';

const CONTENT_BASE = 'https://al-tawheed-content.pages.dev/tawheed';
export const ARABIC_CONTENT_BASE = 'https://al-tawheed-content.pages.dev/tawheed-ar';

/** CDN book cover (same art as Flutter `assets/tawheed.png`). */
export const CDN_COVER_URL = `${CONTENT_BASE}/images/cover.jpg`;

/** Fallback if catalog/CDN is unavailable at build time. */
export const BOOK_COVER_SRC = '/book-cover.png';

export function bookCoverSrc(book?: Book): string {
  return book?.coverImageUrl ?? CDN_COVER_URL;
}

/**
 * Social / structured-data image for content pages (lecture + Arabic pages).
 * Uses the site's own two-series `og-image.png` card, NOT the CDN `cover.jpg`
 * (which is an older single-series Urdu banner — both catalogs point at it, so
 * Arabic shares were showing the wrong series). Keeping this in the web repo
 * means shares always reflect the current, deployed card.
 */
export function bookCoverOgUrl(_book?: Book): string {
  return `${SITE_URL}/og-image.png`;
}

/**
 * Per-lecture social card generated by `scripts/make-og-lectures.mjs`
 * (`npm run og`). Naming convention must match that script exactly.
 */
export function lectureOgImageUrl(lecture: Lecture, chapter?: Chapter): string {
  return `${SITE_URL}/og/lectures/${chapterSlug(chapter?.id ?? lecture.chapterId)}-${lectureSlug(lecture)}.jpg`;
}

/** Per-dars social card for the Arabic series, generated by the same script. */
export function arabicLectureOgImageUrl(lecture: Lecture): string {
  return `${SITE_URL}/og/arabic/${arabicLectureSlug(lecture)}.jpg`;
}

// Every page frontmatter awaits these independently, so memoize at module
// level: one CDN round-trip per file per build instead of dozens, and a
// smaller failure surface. A failed fetch clears its slot so a retry (e.g.
// dev-server reload) isn't stuck with a rejected promise forever.
const fetchCache = new Map<string, Promise<unknown>>();

function fetchJsonCached<T>(url: string, what: string): Promise<T> {
  let promise = fetchCache.get(url) as Promise<T> | undefined;
  if (!promise) {
    promise = (async () => {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`Failed to fetch ${what}: ${res.status}`);
      return res.json() as Promise<T>;
    })();
    promise.catch(() => fetchCache.delete(url));
    fetchCache.set(url, promise);
  }
  return promise;
}

export function getCatalog(): Promise<Catalog> {
  return fetchJsonCached<Catalog>(`${CONTENT_BASE}/catalog.json`, 'catalog');
}

export function getArabicCatalog(): Promise<Catalog> {
  return fetchJsonCached<Catalog>(`${ARABIC_CONTENT_BASE}/catalog.json`, 'Arabic catalog');
}

export function getAppConfig(): Promise<AppConfig> {
  return fetchJsonCached<AppConfig>(`${CONTENT_BASE}/app-config.json`, 'app-config');
}

/** Format seconds → "35m 57s" or "1h 23m" */
export function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  if (h > 0) return `${h}h ${m}m`;
  if (m > 0) return `${m}m ${s > 0 ? s + 's' : ''}`.trim();
  return `${s}s`;
}

function asI18n(field: string | I18nField | undefined): I18nField | null {
  if (!field) return null;
  if (typeof field === 'string') return { en: field };
  return field;
}

/**
 * The site standardized on the assimilated transliteration "Kitab at-Tawheed",
 * but the content CDN's catalog still says "Kitab al-Tawheed". Normalize at
 * the display boundary so every catalog-derived string matches, until the
 * Al-Tawheed-Content repo is updated (see BACKLOG.md).
 */
function normalizeTitleSpelling(s: string): string {
  return s.replace(/Kitab [Aa][lt]-Tawheed/g, 'Kitab at-Tawheed');
}

/**
 * Resolve multilingual content (same fallback chain as Flutter LanguageProvider).
 * roman → ur → en; ur → en; en is terminal.
 */
export function resolve(
  field: string | I18nField | undefined,
  locale: ContentLocale = 'en',
): string {
  const map = asI18n(field);
  if (!map) return '';

  const primary = map[locale];
  if (primary?.trim()) return normalizeTitleSpelling(primary);

  if (locale === 'roman' && map.ur?.trim()) return normalizeTitleSpelling(map.ur);
  return normalizeTitleSpelling(map.en ?? '');
}

/** English string for SEO meta, JSON-LD, and primary headings. */
export function en(field: string | I18nField | undefined): string {
  return resolve(field, 'en');
}

/** Arabic string for RTL UI on Arabic pages. */
export function ar(field: string | I18nField | undefined): string {
  return resolve(field, 'ar');
}

/** Slug from chapter id: "class-01" → "class-01" (already a slug) */
export function chapterSlug(chapterId: string): string {
  return chapterId;
}

/** Slug from lecture id: "lec-001" → "part-01" using the lecture number */
export function lectureSlug(lecture: Lecture): string {
  return `part-${String(lecture.number).padStart(2, '0')}`;
}

/** Slug for Arabic dars: dars-01 … dars-91 */
export function arabicLectureSlug(lecture: Lecture): string {
  return `dars-${String(lecture.number).padStart(2, '0')}`;
}

export function playStoreUrl(appConfig: AppConfig): string {
  return (
    appConfig.links.playStore ??
    'https://play.google.com/store/apps/details?id=com.almarfa.tawheed'
  );
}

export function nextChapter(catalog: Catalog, chapter: Chapter): Chapter | undefined {
  return catalog.chapters.find((c) => c.number === chapter.number + 1);
}

export function firstLectureInChapter(catalog: Catalog, chapterId: string): Lecture | undefined {
  return catalog.lectures
    .filter((l) => l.chapterId === chapterId)
    .sort((a, b) => a.number - b.number)[0];
}
