export interface I18nField {
  en: string;
  ur?: string;
  roman?: string;
  hi?: string;
  ar?: string;
}

/** Matches Flutter [AppLanguage] content resolution keys. */
export type ContentLocale = 'en' | 'ur' | 'roman' | 'ar';

export interface Book {
  id: string;
  title: I18nField;
  titleArabic?: string;
  author?: string;
  speaker: I18nField;
  speakerShortName?: string;
  totalDurationSeconds: number;
  lectureCount: number;
  coverImageUrl: string;
  language: string;
  catalogUpdatedAt?: string;
}

export interface Chapter {
  id: string;
  number: number;
  title: I18nField;
  lectureCount: number;
}

export interface Lecture {
  id: string;
  number: number;
  chapterId: string;
  title: I18nField;
  audioUrl: string;
  durationSeconds: number;
  fileSizeBytes: number;
  description?: string | null;
}

export interface DailyBenefit {
  id: string;
  text: string | I18nField;
  source: string | I18nField;
  textArabic?: string;
}

export interface Catalog {
  version: number;
  book: Book;
  chapters: Chapter[];
  lectures: Lecture[];
  dailyBenefits: DailyBenefit[];
}

export interface AppConfig {
  version: number;
  links: { playStore?: string; appStore?: string; website?: string; youtube?: string };
  contact: { email: string; subject: string };
  share: { message: string };
  about: { appName: string; lecturer: string; lectureCount: number; totalDuration: string };
}

export const SITE_URL = 'https://kitabattawheed.com';

// Cross-promo — "Also by Al Marfa". Al Quran (alquranreader.com) is the
// sister site/app; reciprocal link lives in that repo's footer + About page.
export const ALQURAN_SITE_URL = 'https://alquranreader.com';
export const ALQURAN_PLAY_URL =
  'https://play.google.com/store/apps/details?id=com.almarfa.alquran' +
  '&utm_source=tawheedweb&utm_medium=web&utm_campaign=cross-promo';

const CONTENT_BASE = 'https://al-tawheed-content.pages.dev/tawheed';
export const ARABIC_CONTENT_BASE = 'https://al-tawheed-content.pages.dev/tawheed-ar';

/** CDN book cover (same art as Flutter `assets/tawheed.png`). */
export const CDN_COVER_URL = `${CONTENT_BASE}/images/cover.jpg`;

/** Fallback if catalog/CDN is unavailable at build time. */
export const BOOK_COVER_SRC = '/book-cover.png';

export function bookCoverSrc(book?: Book): string {
  return book?.coverImageUrl ?? CDN_COVER_URL;
}

/**
 * Social / structured-data image for content pages (lecture + Arabic pages).
 * Uses the site's own two-series `og-image.png` card, NOT the CDN `cover.jpg`
 * (which is an older single-series Urdu banner — both catalogs point at it, so
 * Arabic shares were showing the wrong series). Keeping this in the web repo
 * means shares always reflect the current, deployed card.
 */
export function bookCoverOgUrl(_book?: Book): string {
  return `${SITE_URL}/og-image.png`;
}

/**
 * Per-lecture social card generated by `scripts/make-og-lectures.mjs`
 * (`npm run og`). Naming convention must match that script exactly.
 */
export function lectureOgImageUrl(lecture: Lecture, chapter?: Chapter): string {
  return `${SITE_URL}/og/lectures/${chapterSlug(chapter?.id ?? lecture.chapterId)}-${lectureSlug(lecture)}.jpg`;
}

/** Per-dars social card for the Arabic series, generated by the same script. */
export function arabicLectureOgImageUrl(lecture: Lecture): string {
  return `${SITE_URL}/og/arabic/${arabicLectureSlug(lecture)}.jpg`;
}

// Every page frontmatter awaits these independently, so memoize at module
// level: one CDN round-trip per file per build instead of dozens, and a
// smaller failure surface. A failed fetch clears its slot so a retry (e.g.
// dev-server reload) isn't stuck with a rejected promise forever.
const fetchCache = new Map<string, Promise<unknown>>();

function fetchJsonCached<T>(url: string, what: string): Promise<T> {
  let promise = fetchCache.get(url) as Promise<T> | undefined;
  if (!promise) {
    promise = (async () => {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`Failed to fetch ${what}: ${res.status}`);
      return res.json() as Promise<T>;
    })();
    promise.catch(() => fetchCache.delete(url));
    fetchCache.set(url, promise);
  }
  return promise;
}

export function getCatalog(): Promise<Catalog> {
  return fetchJsonCached<Catalog>(`${CONTENT_BASE}/catalog.json`, 'catalog');
}

export function getArabicCatalog(): Promise<Catalog> {
  return fetchJsonCached<Catalog>(`${ARABIC_CONTENT_BASE}/catalog.json`, 'Arabic catalog');
}

export function getAppConfig(): Promise<AppConfig> {
  return fetchJsonCached<AppConfig>(`${CONTENT_BASE}/app-config.json`, 'app-config');
}

/** Format seconds → "35m 57s" or "1h 23m" */
export function formatDuration(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = seconds % 60;
  if (h > 0) return `${h}h ${m}m`;
  if (m > 0) return `${m}m ${s > 0 ? s + 's' : ''}`.trim();
  return `${s}s`;
}

function asI18n(field: string | I18nField | undefined): I18nField | null {
  if (!field) return null;
  if (typeof field === 'string') return { en: field };
  return field;
}

/**
 * The site standardized on the assimilated transliteration "Kitab at-Tawheed",
 * but the content CDN's catalog still says "Kitab al-Tawheed". Normalize at
 * the display boundary so every catalog-derived string matches, until the
 * Al-Tawheed-Content repo is updated (see BACKLOG.md).
 */
function normalizeTitleSpelling(s: string): string {
  return s.replace(/Kitab [Aa][lt]-Tawheed/g, 'Kitab at-Tawheed');
}

/**
 * Resolve multilingual content (same fallback chain as Flutter LanguageProvider).
 * roman → ur → en; ur → en; en is terminal.
 */
export function resolve(
  field: string | I18nField | undefined,
  locale: ContentLocale = 'en',
): string {
  const map = asI18n(field);
  if (!map) return '';

  const primary = map[locale];
  if (primary?.trim()) return normalizeTitleSpelling(primary);

  if (locale === 'roman' && map.ur?.trim()) return normalizeTitleSpelling(map.ur);
  return normalizeTitleSpelling(map.en ?? '');
}

/** English string for SEO meta, JSON-LD, and primary headings. */
export function en(field: string | I18nField | undefined): string {
  return resolve(field, 'en');
}

/** Arabic string for RTL UI on Arabic pages. */
export function ar(field: string | I18nField | undefined): string {
  return resolve(field, 'ar');
}

/** Slug from chapter id: "class-01" → "class-01" (already a slug) */
export function chapterSlug(chapterId: string): string {
  return chapterId;
}

/** Slug from lecture id: "lec-001" → "part-01" using the lecture number */
export function lectureSlug(lecture: Lecture): string {
  return `part-${String(lecture.number).padStart(2, '0')}`;
}

/** Slug for Arabic dars: dars-01 … dars-91 */
export function arabicLectureSlug(lecture: Lecture): string {
  return `dars-${String(lecture.number).padStart(2, '0')}`;
}

export function playStoreUrl(appConfig: AppConfig): string {
  return (
    appConfig.links.playStore ??
    'https://play.google.com/store/apps/details?id=com.almarfa.tawheed'
  );
}

export function nextChapter(catalog: Catalog, chapter: Chapter): Chapter | undefined {
  return catalog.chapters.find((c) => c.number === chapter.number + 1);
}

export function firstLectureInChapter(catalog: Catalog, chapterId: string): Lecture | undefined {
  return catalog.lectures
    .filter((l) => l.chapterId === chapterId)
    .sort((a, b) => a.number - b.number)[0];
}

// ── Kitab at-Tawheed matn (Arabic book text) ───────────────────────────────
//
// The book text is authored/edited in the mobile app (Al-Tawheed) and shipped
// there as a bundled asset. We commit an identical copy under src/data/ and
// keep it in sync with `npm run sync:book`. The matn is Arabic-only and never
// translated. See BACKLOG.md.
import bookArData from '../data/book_tawheed-ar.json';

export interface BookMeta {
  title: string;
  author: string;
}

export interface BookChapter {
  /** "ch-00" … "ch-66" — also the URL slug. */
  id: string;
  number: number;
  /** Arabic bab title (fully vocalized). */
  title: string;
  /** Plain text, \n-separated blocks, with {verse} / ((hadith)) / [citation] markers. */
  text: string;
}

export interface ArabicBook {
  book: BookMeta;
  chapters: BookChapter[];
}

/** The bundled Arabic matn — 67 chapters (ch-00 opening + ch-01…ch-66 babs). */
export function getArabicBook(): ArabicBook {
  return bookArData as ArabicBook;
}

const HTML_ESCAPE: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
};

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) => HTML_ESCAPE[c]);
}

/**
 * Render a chapter's plain-text matn to trusted HTML, mirroring the mobile app
 * reader's three-token parse:
 *   {…}   → verse   (ornate mushaf brackets ﴾…﴿, green)
 *   ((…)) → hadith  (guillemets «…», amber)
 *   […]   → citation (surah:ayah, cyan)
 * Blocks split on \n become <p> paragraphs. Input is escaped first, so the only
 * markup in the output is the spans this function emits.
 */
export function bookChapterHtml(text: string): string {
  const markup = escapeHtml(text)
    .replace(/\{([^{}]+)\}/g, '<span class="ayah">﴾$1﴿</span>')
    .replace(/\(\(([^()]+)\)\)/g, '<span class="hadith">«$1»</span>')
    .replace(/\[([^[\]]+)\]/g, '<span class="citation">[$1]</span>');

  return markup
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => `<p>${line}</p>`)
    .join('\n');
}
